---
- name: Install lsyncd
  yum: pkg=lsyncd state=present

- name: Create logging directories
  file: dest={{lsyncd_logging_dir}} state=directory

- name: Create logging files "{{item}}"
  file:
    dest: "{{ item }}"
    state: touch
  with_items:
    - "{{lsyncd_logging_dir}}/{{lsyncd_logging_file}}"
    - "{{lsyncd_logging_dir}}/{{lsyncd_logging_status_file}}"

- name: Enable lsyncd at startup
  service: name=lsyncd enabled=yes
  when: lsyncd_startup_enabled == True
